# Generated by Django 5.2.4 on 2025-08-01 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_journalentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(default=datetime.date(2025, 8, 1), max_length=100),
        ),
    ]
