# Generated by Django 5.2.4 on 2025-08-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_journalentry_options_alter_journalentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
