# Generated by Django 5.2.5 on 2025-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='consecutive_submissions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
