# Generated by Django 5.2.5 on 2025-08-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_dailygoals_consecutive_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoals',
            name='consecutive_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
