# Generated by Django 5.2.5 on 2025-08-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_dailygoals_consecutive_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailygoals',
            name='goal_completed',
        ),
    ]
