# Generated by Django 5.2.5 on 2025-08-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_dailygoals_goal_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailygoals',
            options={'ordering': ['id']},
        ),
    ]
