# Generated by Django 5.2.5 on 2025-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_dailygoals_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoals',
            name='submissions_total',
            field=models.IntegerField(default=0),
        ),
    ]
