# Generated by Django 5.2.5 on 2025-08-28 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_dailygoals_submissions_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydrationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_intake', models.IntegerField(default=0)),
                ('max_water', models.IntegerField(default=0)),
                ('date_of_intake', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_of_intake'],
            },
        ),
    ]
