# Generated by Django 5.2.5 on 2025-09-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_hydrationtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrationtracker',
            name='water_intake',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
