# Generated by Django 5.2.5 on 2025-09-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_hydrationtracker_water_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrationtracker',
            name='water_intake',
            field=models.PositiveIntegerField(choices=[(8, '8 oz'), (16, '16 oz'), (32, '32 oz')], default=0),
        ),
    ]
