# Generated by Django 5.2.5 on 2025-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_hydrationtracker_water_intake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydrationtracker',
            options={'ordering': ['-date_of_intake']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='Profile', max_length=100),
        ),
    ]
