# Generated by Django 5.2.5 on 2025-09-20 19:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_hydrationtracker_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='journal_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
